### ISSUE TITLE
JBossServerLogTailSplitter doesn't read specific exception message

### ISSUE THREAD

**Issue by trohovsky** [triceo/splitlog#57]
It reads http://pastebin.test.redhat.com/301592, but this it doesn't read http://pastebin.test.redhat.com/301593.

**Comment by triceo** [comment]
Thanks for reporting, will take a look ASAP.

**Comment by trohovsky** [comment]
I am using splitlog 1.6.0.

**Comment by triceo** [comment]
Found it and fixed it. Turns out Splitlog didn't expect exception causes to have more than one line. I will release 1.7.2 in the near future.

**Comment by triceo** [comment]
1.7.2 released and will soon sync to Maven Central
